version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      spring:
        patterns:
          - "org.springframework*"
          - "org.springdoc*"
      testing:
        patterns:
          - "org.junit*"
          - "org.testcontainers*"
          - "org.mockito*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
